---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/deployment

namespace: kube-system

configMapGenerator:
  - name: swisnap-k8s-configmap
    behavior: merge
    literals:
      - SWISNAP_ENABLE_KUBERNETES_LOGS=false

images:
  - name: solarwinds/solarwinds-snap-agent-docker
    newTag: 4.4.0-4.5.0.1550
