---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/deployment

namespace: kube-system

configMapGenerator:
  - name: swisnap-k8s-configmap
    behavior: merge
    literals:
      - SWISNAP_ENABLE_KUBERNETES_LOGS=false

images:
  - name: 858939916050.dkr.ecr.us-east-1.amazonaws.com/host-agent-docker-images
    newTag: circleci_build_5a44c386-e043-4817-8c8f-0480c1482f20
