---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/daemonset


configMapGenerator:
  - name: swisnap-host-configmap
    behavior: merge
    literals:
      - SWISNAP_ENABLE_DOCKER_LOGS=false

images:
  - name: solarwinds/solarwinds-snap-agent-docker
    newTag: 4.3.0-4.1.0.1024
