---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/daemonset

namespace: kube-system

configMapGenerator:
  - name: swisnap-host-configmap
    behavior: merge
    literals:
      - SWISNAP_ENABLE_DOCKER_LOGS=false
      - SWISNAP_DOCKER_LOGS_CONTAINER_NAMES=""

images:
  - name: solarwinds/solarwinds-snap-agent-docker:latest
    newName: swipoleszcz/swidummy
    newTag: latest

spec:
  template:
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        # - name: dockershim-sock
        #   hostPath:
        #     path: /var/run/dockershim.sock
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock

      containers:
      - name: swisnap-agent-ds
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          # - name: dockershim-sock
          #   mountPath: /var/run/dockershim.sock
          - name: containerd-sock
            mountPath: /run/containerd/containerd.sock
