---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: swisnap-agent-k8s-event-collector
  namespace: kube-system
  labels:
    app: swisnap-agent-k8s-event-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swisnap-agent-k8s-event-collector
  template:
    metadata:
      labels:
        app: swisnap-agent-k8s-event-collector
    spec:
      serviceAccountName: swisnap-events-agent-serviceaccount
      containers:
        - name: swisnap-agent-k8s-event-collector
          image: 'solarwinds/solarwinds-snap-agent-docker:latest'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugins-logs
              mountPath: /opt/SolarWinds/Snap/etc/plugins.d/logs.yaml
              subPath: logs.yaml
            - name: plugins-kubernetes
              mountPath: /opt/SolarWinds/Snap/etc/plugins.d/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: tasks-aokubernetes
              mountPath: /opt/SolarWinds/Snap/etc/tasks.d/task-aokubernetes.yaml
              subPath: task-aokubernetes.yaml
            - name: tasks-logs
              mountPath: /opt/SolarWinds/Snap/etc/tasks.d/task-logs.yaml
              subPath: task-logs.yaml
          env:
            - name: APPOPTICS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: appoptics-token
                  key: APPOPTICS_TOKEN
                  optional: true
            - name: SOLARWINDS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: solarwinds-token
                  key: SOLARWINDS_TOKEN
                  optional: true
          envFrom:
            - configMapRef:
                name: swisnap-agent-k8s-events-configmap
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /v1/plugins
              port: 21413
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/plugins
              port: 21413
            initialDelaySeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: plugins-logs
          configMap:
            name: plugin-configs
            items:
              - key: logs.yaml
                path: logs.yaml
        - name: plugins-kubernetes
          configMap:
            name: plugin-configs
            items:
              - key: kubernetes.yaml
                path: kubernetes.yaml
        - name: tasks-logs
          configMap:
            name: task-manifests
            items:
              - key: task-logs.yaml
                path: task-logs.yaml
        - name: tasks-aokubernetes
          configMap:
            name: task-manifests
            items:
              - key: task-aokubernetes.yaml
                path: task-aokubernetes.yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
