---
apiVersion: v1
kind: List
items:
  # Service Account for swisnap-events-agent-k8s
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: swisnap-events-agent-serviceaccount
      namespace: kube-system
  # Create ClusterRole that enables swisnap-agent-k8s to access requisite kube-api resources
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: swisnap-events-agent-clusterrole
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["*"]
        resources: ["deployments"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["get", "list", "watch"]
  # Bind the swisnap-events-agent-clusterrole with the swisnap-events-agent-serviceaccount we created above
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: swisnap-events-agent-clusterrolebinding
    subjects:
      - kind: ServiceAccount
        name: swisnap-events-agent-serviceaccount
        namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: swisnap-events-agent-clusterrole
